### ISSUE TITLE
Outdated base docker image

### ISSUE THREAD

**Issue by sergidomenechguzy** [WSE-research/Qanary-NER-automl-component#2]
​To use the NER automl component with custom training data a basic docker image without pretrained models is provided on docker hub: [qanary/qanary-component-ner-automl](https://hub.docker.com/r/qanary/qanary-component-ner-automl).

But this image was last updated on January 9 and seems to be outdated and broken. The training with custom data as CSV files worked and correct annotations were also saved to the qanary triple store. But the qanary pipeline never returned any response and instead logged timeout errors and after some time returned an internal server error.

This problem did not occur when cloning the repository instead of using the docker image and was also fixed when using one of the new pretrained images while still triggering a retrain with custom CSV data.

So I think this is easily fixed by simply updating the image as newer versions don't have this problem.

**Comment by AnnemarieWittig** [comment]
Hi @sergidomenechguzy !

Thank you for bringing this to my attention. This image is actually just a "leftover" from previous iterations. Please refer to the images listed in the [README](https://github.com/WSE-research/Qanary-NER-automl-component#ready-to-go-docker-images) for the current images. I will remove the one you listed shortly!
